management:
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sample?createDatabaseIfNotExist=true
    username: root
    password: Rootpassword@123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

