server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Irushinie/microservices-second-config-store
          default-label: master
          search-paths:
            - 'service-config/*service'
