spring:
  datasource:
    url: jdbc:mysql://localhost:3307/taskdb?createDatabaseIfNotExist=true
    username: root
    password: Rootpassword@123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: task
